### ISSUE TITLE
formattedPrice.substr is not a function

### ISSUE THREAD

**Issue by currenthandle** [alocke12992/migrating-to-single-spa-react-starter#2]
- Cloned repo
- cd into project dir
- `yarn`
- `yarn start`

src/components/shelf/Product.js:43

TypeError: formattedPrice.substr is not a function

**Comment by jamietre** [comment]
This isn't fixed -- `formattedPrice` function should convert return arg to string in default case

**Comment by jwfriese** [comment]
I can confirm that this is not fixed -- I ran the commands exactly as printed on https://single-spa.js.org/docs/migrating-react-tutorial#project-setup and the app does not run. The error I get in the browser is exactly as indicated in this issue. 

@caseysiebel I think we should reopen this thread

**Comment by LJJCherry** [comment]
This isn't fixed
